# #################################
# Basic training parameters
# To train a different model, change "!include:" statement to new model file
# To compute loss in the time domain, switch "waveform_target" to True
# Authors:
#  * Szu-Wei Fu 2021
#  * Peter Plantinga 2020, 2021
# #################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 7254
# mode: val
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

data_folder: !PLACEHOLDER # e.g, /data/member1/user_jasonfu/noisy-vctk-16k
mode: !PLACEHOLDER
# train_clean_folder: !ref <data_folder>/clean/train/
# train_clean_folder: /vision/vision_users/changan/learn_speech_by_visual/learning-to-hear-by-seeing/data/lhs_all_rir/train
valid_frequency: 1
val_epoch: 1

src_data_folder: /vision/vision_users/changan/lhs_v1
train_clean_folder: !ref <src_data_folder>/train
train_noisy_folder: !ref <data_folder>/noisy/train/
valid_clean_folder: !ref <data_folder>/clean/val/
test_clean_folder: !ref <data_folder>/clean/test/

MetricGAN_folder: !ref <output_folder>/train_enhanced_wavs
MetricGAN_clean_folder: !ref <output_folder>/clean_enhanced_wavs
output_folder: !ref ./results/MetricGAN/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
enhanced_folder: !ref <output_folder>/enhanced_wavs

# Basic parameters
use_tensorboard: True
tensorboard_logs: !ref <output_folder>/logs/

# FFT paremeters
Sample_rate: 16000
# Win_length: 32
# Hop_length: 16
Win_length: 25
Hop_length: 10
N_fft: 512
window_fn: !name:torch.hamming_window

# Data files
# train_annotation: !ref <data_folder>/train.csv
# valid_annotation: !ref <data_folder>/val.csv 
# test_annotation: !ref <data_folder>/test.csv

train_annotation: !ref <src_data_folder>/train.csv
valid_annotation: !ref <src_data_folder>/val.csv 
test_annotation: !ref <src_data_folder>/test.csv

skip_prep: False

# The target metrics that you want to optimize.
# Right now we only support 'pesq' and 'stoi'.
# (Of course, it can be any arbitary metric.)
target_metric: pesq
# Training Parameters
number_of_epochs: 1200
number_of_samples: 256
min_mask: 0
train_N_batch: 8
valid_N_batch: 400
history_portion: 0.2
G_lr: 0.0005
D_lr: 0.0005
mse_weight: 0

dataloader_options:
    batch_size: !ref <train_N_batch>
valid_dataloader_options:
    batch_size: !ref <valid_N_batch>

# Change this import to use a different model
models: !include:../models/MetricGAN.yaml
    N_fft: !ref <N_fft>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

modules:
    generator: !ref <models[generator]>
    discriminator: !ref <models[discriminator]>

g_opt_class: !name:torch.optim.Adam
    lr: !ref <G_lr>
d_opt_class: !name:torch.optim.Adam
    lr: !ref <D_lr>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <models[generator]>
        counter: !ref <epoch_counter>

compute_cost: !name:speechbrain.nnet.losses.mse_loss

compute_STFT: !new:speechbrain.processing.features.STFT
    sample_rate: !ref <Sample_rate>
    win_length: !ref <Win_length>
    hop_length: !ref <Hop_length>
    n_fft: !ref <N_fft>
    window_fn: !ref <window_fn>

compute_ISTFT: !new:speechbrain.processing.features.ISTFT
    sample_rate: !ref <Sample_rate>
    win_length: !ref <Win_length>
    hop_length: !ref <Hop_length>
    window_fn: !ref <window_fn>

resynth: !name:speechbrain.processing.signal_processing.resynthesize
    stft: !ref <compute_STFT>
    istft: !ref <compute_ISTFT>
    normalize_wavs: False

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

# Tensorboard logger (optional)
tensorboard_train_logger: !new:speechbrain.utils.train_logger.TensorboardLogger
    save_dir: !ref <tensorboard_logs>
